# ---------------------- CONFIGURACION DE PLUGIN TECHIBERIA ----------------------
# Creado por Nachogamer1000
# 
# mensaje-bienvenida -> mostrar o no el mensaje de bienvenida al unirse al servidor
# mensaje-bienvenida-texto -> texto entre "" que se mostrara al unirse al servidor. Acepta codigo colores [%player% -> nombre del jugador]
#
# active -> Activar el respawneo de shulkers
# rate -> Tiempo de espera entre cada tanda
# cantidadMaxPorTanda -> Cantidad de shulkers maxima por tanda
# probabilidadBloqueValido -> Probabilidad 1 entre X de que el bloque sea valido
# chunkRadio -> radio de chunks a los que se debe estar de una endCity (Aviso: Los numero mayores de 8 pueden causar problemas)
#
# OPplayers -> Lista en la que estan los jugadores con permisos especiales
# donadoresPlayers -> Lista en la que estan los donadores
# miembrosPlayers -> Lista en la que estan los miembros
#
config:
    mensaje-bienvenida: true
    mensaje-bienvenida-texto: "&7&lHola &6&l%player%, &7&lbienvenido a &4&lTechIberia"
    mensaje-bienvenida-texto-OP: "&7&lHola &c&l%player%, &7&lbienvenido a &4&lTechIberia"
    mensaje-bienvenida-texto-donador: "&7&lHola &b&l%player%, &7&lbienvenido a &4&lTechIberia"
    mensaje-bienvenida-texto-miembro: "&7&lHola &2&l%player%, &7&lbienvenido a &4&lTechIberia"
    mensaje-bienvenida-texto-admin: "&7&lHola &6&l%player%, &7&lbienvenido a &4&lTechIberia"
    
    mecanicas:
       active: true
       rate: 600
       cantidadMaxPorTanda: 5
       probabilidadBloqueValido: 10
       chunkRadio: 5
        
Scoreboard:
   active: false
   ticks: 20
   title: "TehcIberiaSMP"
   text:
      - "&4Tech&6Iberia&1SMP"
      - ""
      - "&d%player%"
      - ""
      - "&3&l&nCoordenadas"
      - "&eX: &2%posX%"
      - "&eY: &2%posY%"
      - "&eZ: &2%posZ%"


OPplayers:
    - Nachogamer1000
    - Misk0_Jones
    
donadoresPlayers:
    - Saawel
    
miembrosPlayers:

adminsPlayers:
    
   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    